### ISSUE TITLE
reactjs에 bootstrap 적용

### ISSUE THREAD

**Issue by tmheo** [iingyeo/iingyeo_frontend#10]
reactjs-bootstrap(http://react-bootstrap.github.io/components.html) 라이브러리가 있으나
이 라이브러리를 사용하면 기본 reactjs 문법이 달라져서 기본 문법도 잘 모르는 상태에서 reactjs-bootstrap 문법까지 익혀야 하는 어려움이 있음..

http://react-bootstrap.github.io/components.html 를 그대로 사용할 건지 아니면 bootstrap 을 가져오고 활용하는 방식으로 할 것인지 결정 필요

**Comment by kang1224** [comment]
Duplicate of #20
